-- 알림 설정 테이블

CREATE TABLE meal_alarm_settings (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL UNIQUE,
    morning_hour NUMBER(2) DEFAULT 8 CHECK (morning_hour BETWEEN 0 AND 23),
    morning_minute NUMBER(2) DEFAULT 0 CHECK (morning_minute BETWEEN 0 AND 59),
    lunch_hour NUMBER(2) DEFAULT 12 CHECK (lunch_hour BETWEEN 0 AND 23),
    lunch_minute NUMBER(2) DEFAULT 0 CHECK (lunch_minute BETWEEN 0 AND 59),
    dinner_hour NUMBER(2) DEFAULT 18 CHECK (dinner_hour BETWEEN 0 AND 23),
    dinner_minute NUMBER(2) DEFAULT 0 CHECK (dinner_minute BETWEEN 0 AND 59),
    alarm_enabled NUMBER(1) DEFAULT 1 CHECK (alarm_enabled IN (0, 1)),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);