-- 푸시 토큰 저장 테이블

CREATE TABLE meal_alarm_tokens (
    idx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL, -- unique 아닌 이유 : 사용자별 기기가 여러대 가능성
    token VARCHAR2(1024) NOT NULL UNIQUE,
    platform VARCHAR2(20) NOT NULL CHECK (platform IN ('android', 'ios')),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    FOREIGN KEY (customer_id) REFERENCES customers(idx) ON DELETE CASCADE
);